### PR TITLE
fix: test-short tests

### LINKED ISSUE #121: `make test-short` fails
## Context

I'm working on another PR. `make test-short` fails on the feature/fibre branch. 

See https://gist.github.com/rootulp/f677db27c9d498ab96d6ac835e224e2e

## Problem

Failing tests:
- `TestKeeperTestSuite/TestValidatePaymentPromiseInternal`
- `TestServerUploadShard/InvalidRowAssignment`

also a ton of warn logs about failing to upload rows.

### PR DESCRIPTION
**Pull request by rootulp**
Closes https://github.com/celestiaorg/celestia-app-fibre/issues/121

I should've included part of this diff in https://github.com/celestiaorg/celestia-app-fibre/pull/110 but it wasn't obvious if I broke test-short b/c it was failing before my change.

## Testing

```
make test-short
```

passes

### CODE REVIEW

File: fibre/client_upload_test.go [hunk 1]
```diff
@@ -353,13 +353,19 @@ func (v *validatorMockClient) UploadShard(ctx context.Context, req *types.Upload
 		return nil, err
 	}
 
+	// Wrap sign bytes with domain separation (matching client_upload.go)
+	validatorSignBytes, err := core.RawBytesMessageSignBytes("celestia", fibre.SignBytesPrefix, signBytes)
```
Comment (Wondertan) [inline fibre/client_upload_test.go]: Chain id is available on pp, no need to hardcode

File: fibre/server_upload_test.go [hunk 2]
```diff
@@ -93,7 +93,7 @@ func TestServerUploadShard(t *testing.T) {
 			},
 			check: func(t *testing.T, resp *types.UploadShardResponse, err error) {
 				require.Error(t, err)
-				require.Contains(t, err.Error(), "row assignment verification failed")
+				require.Contains(t, err.Error(), "shard assignment verification failed")
```
Comment (Wondertan) [inline fibre/server_upload_test.go:96]: I see, so the test assertion wasnt not updated in that renaming PR. Another reason to keep errors always as values, which i forgot to do.

File: fibre/client_upload_test.go (hunk 1 above)
Comment (Wondertan) [reply fibre/client_upload_test.go]: While we on it, i would iterate on the idea of making  this a method on PP. Not a part of existing SignBytes (which wouldnt work as explained in the previous PR) but a new additional one. (E.g. ValidatorSignBytes)

This wont just be a change to improve ergonomics for accessing bytes to sign, but will also keep this signing quirk contained in a single spot, preventing misuse and making it easy to evolve/change the PP. The users wouldnt need to import the core pkg, pass anything to this hacky function, i.e. the complexity of understanding what to sign is abstracted. Oh, and also the SignBytesPrefix can then be back privatised.

**Review by Wondertan — DISMISSED** [review]

**Comment by Wondertan** [comment]
(Approve was misclick)

**Review by evan-forbes — DISMISSED** [review]

File: fibre/client_upload_test.go (hunk 1 above)
Comment (rootulp) [reply fibre/client_upload_test.go]: Removed the hard-coded "celestia" in [db60aee](https://github.com/celestiaorg/celestia-app-fibre/pull/126/commits/db60aee4ea2ca7b4de4eed503b2de918a457e1dd)

Comment (rootulp) [reply fibre/client_upload_test.go]: Opened https://github.com/celestiaorg/celestia-app-fibre/issues/128 b/c not doing it in this PR

**Review by Wondertan — APPROVED** [review]
